### ISSUE TITLE
Read a model file

### ISSUE THREAD

**Issue by JoaoLeal12** [patrikhuber/eos-model-viewer#1]
Hello.
What file should be given to the fuction that loads the model? And how to generate that file?

Thanks!

**Comment by patrikhuber** [comment]
Hi,

The readme pretty much says it:

> This is a viewer that displays Morphable Models from the eos Morphable Model library (github.com/patrikhuber/eos).

So you give it the model and blendshape file from the share/ directory.

**Comment by JoaoLeal12** [comment]
Oh, I think I missunderstood the objective of the viewer. 
I thought it would also be able to display the models generated previously by eos.
I'm sorry.

**Comment by patrikhuber** [comment]
I'm not sure I understand. Yes, the purpose of the viewer is to display models used by eos.

**Comment by JoaoLeal12** [comment]
Yes, but I thought it would also display the ones generated by the eos, with the input of a face picture. Where can the .obj or .mtl be used?

**Comment by patrikhuber** [comment]
Any mesh viewer / graphics tool, MeshLab, Blender, etc.

**Comment by JoaoLeal12** [comment]
Oh, nice, just did it, thanks!
Btw, is there any way to draw a colored mesh in c++?
What i mean is : what is the correspondence that i can make(code wise) to color the mesh that the morphablemodel object already has.
Sorry if that question sounded messy, but I just want to be able to show the colored mesh in c++ and then also change some of its parameters.

**Comment by patrikhuber** [comment]
Cool.

I'm not exactly sure what you want to do, but I think you'd need to acquire the shape & colour model (link see eos readme), as eos includes only the shape model without the colour PCA. Other than that it sounds like you need to read, learn and experiment a bit more by yourself to find out what you actually want to do.

**Comment by JoaoLeal12** [comment]
Alright, thanks!
Will send a mail asking if I could use the shape and colour model.
