### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [patrikhuber/eos-model-viewer#11]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/patrikhuber/eos-model-viewer/blob/00d56f2548547753ed097398733db65b42f7dc6a/eos-model-viewer.cpp#L53 "main() function")” does not contain [a catch-all handler](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by patrikhuber** [comment]
Hi,

As noted in the readme, the viewer is seriously unpolished code, it's a quickly hacked-together thing that I use for myself internally and I thought I make available online because it could be useful to others.

> Note: The viewer works well, but the code is not very polished and will crash if you do unexpected things (e.g. cancel the loading dialogues). The CMake scripts are in serious alpha-stage - You are on your own compiling it!

However, it's great if we can improve it. Where do you want to add the try/catch? Presumably around [`viewer.launch();`](https://github.com/patrikhuber/eos-model-viewer/blob/4244cb0d168afdd45f54bf59f64c57b906fca512/eos-model-viewer.cpp#L576)?
Do you think a catch-all (`...`) is a good idea? Isn't there a guideline that says we should only catch the exceptions that we can actually handle, and pass the rest on to the callee? Or does that guideline not apply to `main()`?

Feel free to open a PR!

**Comment by elfring** [comment]
>Do you think a catch-all (...) is a good idea?

[The available information sources](https://www.learncpp.com/cpp-tutorial/144-uncaught-exceptions-catch-all-handlers-and-exception-specifiers/ "Uncaught exceptions, catch-all handlers, …") can provide incentives for software design adjustments, can't they?

**Comment by patrikhuber** [comment]
> The available information sources can provide incentives for software design adjustments, can't they?

They can, but there's also tons of old, outdated and wrong information out there. Finding out which source is "good", reliable or up-to-date is often considerable effort.

For example, your link suggests this:

```
#include <iostream>
int main()
{
 
    try
    {
        runGame();
    }
    catch(...)
    {
        std::cerr << "Abnormal termination\n";
    }
 
    saveState(); // Save user's game
    return 1;
}
```

From what I have learned and from my experience (which could very possibly be wrong here!), I would rather do the following:

```
#include <iostream>
int main()
{
 
    try
    {
        runGame();
    }
    catch(...)
    {
        std::cerr << "Abnormal termination\n";
        saveState(); // Save user's game
        throw; // re-throw the exception to the callee - not 100% sure that's how you do it
    }
    return 0;
}
```
Does what I think make sense? Which one is better? Sure it could be researched, it would take me a couple of hours or so, and I am a bit of a perfectionist in general, but for this model-viewer, currently, it is not worth it for me personally. But I think it sounds like your C++ knowledge/experience is much bigger than mine, so if you already know the best practice in this case, I would be very happy to accept a PR! :-)

**Comment by elfring** [comment]
>But I think it sounds like your C++ knowledge/experience is much bigger than mine, …

Such an impression can distract from an other solution.

* Does your evolving model viewer manage any data which should be safely stored (at the end)?
* Have you got any software development opinions for [the following information](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?
  ```
  If there are no containing try-blocks left, std::terminate is executed
  (in this case, it is implementation-defined whether any stack unwinding occurs
  at all: throwing an uncaught exception is permitted to terminate the program
  without invoking any destructors).
  ```

**Comment by elfring** [comment]
>No, it doesn't modify anything at all.

This can be fine for a simple data viewer.

I assumed from a glimpse at the published screenshot that display parameters could be adjusted. (The draw options and coefficients did not look as greyed-out/read-only settings in the graphical user interface.)

**Comment by elfring** [comment]
I checked only the general change acceptance for further software evolution so far.

**Comment by patrikhuber** [comment]
> I checked only the general change acceptance for further software evolution so far.

What? I'm sorry but this sentence does not make too much sense to me.

I don't think we're getting anywhere here. Actually, upon further inspection of your GitHub profile, I found that you posted a very similar issue in dozens of other GitHub repositories over the last couple of days, and you very often reply with the same, apparently pre-written comment messages. I'm really not sure what your goal here is, but I am closing this for now, until there's some substantial reason to re-open this or if you are really interested in contributing.

**Comment by elfring** [comment]
I identified the possibility for another software change around the implementation also of this model viewer.
:crystal_ball: It can become interesting then under which circumstances possible changes will be integrated somehow, can't it?
