### ISSUE TITLE
issue happens when cloning this repo.

### ISSUE THREAD

**Issue by bigdimboom** [patrikhuber/eos-model-viewer#3]
![image](https://user-images.githubusercontent.com/6119906/37671576-61004ace-2c42-11e8-9fb8-9466028f6e0f.png)

Is it your private repo?

**Comment by patrikhuber** [comment]
This needs fixing, thank you for reporting it!

We are now using the official eigen-git-mirror: https://github.com/eigenteam/eigen-git-mirror

I will fix this soon, in the meantime you could change the submodule URL locally.

**Comment by patrikhuber** [comment]
Actually this is because eos-model-viewer uses an older eos version. So you could try to pull the latest eos master branch inside the `external/` directory of this repo. I am not sure it will go without build errors though as eos has undergone some updates!

**Comment by patrikhuber** [comment]
This is now fixed in the [update-eos-and-igl branch](https://github.com/patrikhuber/eos-model-viewer/tree/update-eos-and-igl). Unfortunately libigl changed their GUI system from nanogui to ImGui, so I had to rewrite the whole GUI.
I'm leaving this issue open until I merge the new branch to master.

**Comment by anny0316** [comment]
![image](https://user-images.githubusercontent.com/43496750/49871954-911a6680-fe52-11e8-8d94-3bd32344b208.png)
The same issue to me, Would you please help me to find out where is the problem. Thank you！

**Comment by patrikhuber** [comment]
@anny0316 Can you please clone/checkout the [update-eos-and-igl branch](https://github.com/patrikhuber/eos-model-viewer/tree/update-eos-and-igl)?

**Comment by anny0316** [comment]
![image](https://user-images.githubusercontent.com/43496750/49875097-1dc92280-fe5b-11e8-8166-89198133dba5.png)
Hello Huber，I clone this branch: update-eos-and-igl branch, but, in the end, it failed.

**Comment by patrikhuber** [comment]
Yea... this is that problem (https://libigl.github.io/rewritten-history/).

**Comment by patrikhuber** [comment]
I've fixed/updated the libigl submodule, merged all changes into `master`, and removed the `update-eos-and-igl` branch. This should all be fixed now. Please use the `master` branch (which is now again the only branch).

**Comment by anny0316** [comment]
Hello, this problem has been solved. Thank you. But how to load colour PCA models?
